#!/bin/bash
clear
function _string() { perl -le 'print map {(a..z,A..Z,0..9)[rand 62] } 0..pop' 15 ; }
VERSION=1.3.6
ip=`/sbin/ifconfig | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'|grep -v "^127"|head -n1`
tmpfile="/tmp/`_string`"
genpass=`_string`
OK=`echo -e "[ \e[0;32mDONE\e[00m ]"`
dPORT=$((RANDOM%64025+1024))
DEBIAN_FRONTEND=noninteractive

function _locale() {
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/default/locale
if [[ -e /usr/sbin/locale-gen ]]; then 
	locale-gen >/dev/null 2>&1
else 
	apt-get update >/dev/null
	apt-get install locale-gen --yes --force-yes >/dev/null 2>&1
	locale-gen >/dev/null 2>&1	
fi
}

function _cronfile() { 
echo -n "Writing ${username} system crontab script ... "
cat >/home/${username}/.startup<<EOF
#!/bin/bash
export USER=\$(id -un)
IRSSI_CLIENT=yes
RTORRENT_CLIENT=yes
DELUGED_CLIENT=yes
DELUGED_PORT=$dPORT
DELUGEWEB_CLIENT=
DELUGEWEB_PORT=
WIPEDEAD=yes
ADDRESS=$(/sbin/ifconfig | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'|grep -v "^127"|head -n1)
if [ "$WIPEDEAD" == "yes" ]; then screen -wipe >/dev/null 2>&1; fi

# NO NEED TO EDIT PAST HERE!
if [ "\$IRSSI_CLIENT" == "yes" ]; then 
	(screen -ls|grep irssi > /dev/null || (screen -fa -dmS irssi irssi && false))
fi

if [ "\$RTORRENT_CLIENT" == "yes" ]; then 
	(screen -ls|grep rtorrent >/dev/null || (screen -fa -dmS rtorrent rtorrent && false))
fi

if [ "\$DELUGED_CLIENT" == "yes" ]; then 
	(pgrep -u \$USER deluged >/dev/null || (deluged -i \$ADDRESS -p \$DELUGED_PORT && false))
fi

if [ "\$DELUGEWEB_CLIENT" == "yes" ]; then 
	(pgrep -u \$USER deluge-web >/dev/null || (deluge-web -f --port=\$DELUGEWEB_PORT --fork && false))
fi
EOF
	chown ${username}.${username} /home/${username}/.startup
	chmod +x ${username}.${username} /home/${username}/.startup
	sudo -u ${username} touch ${tmpfile}
	sudo -u ${username} crontab -l > ${tmpfile}
	echo "*/1 * * * * /home/${username}/.startup">>${tmpfile}
	sudo -u ${username} crontab ${tmpfile}
echo ${OK}
}

function _addduser() {
	echo -n "Do you wish to add a user? (Y/n) "
	read answer
	case ${answer} in
	        [yY] | [yY][Ee][Ss] | "" )
	user=yes
		;;
		[nN] | [nN][Oo] )
	user=no
		;;
		*)
		echo "you selected the wrong one, im going to assume yes"
		user=yes
		;;
	esac	
	if [[ ${user} == "no" ]]; then echo -n "Run deluge as who? (THERE MUST BE A USERNAME HERE) "
		read username
		MD5=`echo ${genpass}|md5sum|awk '{print $1}'`
	fi
	if [[ ${user} == "yes" ]]; then
	echo -n "Username: "; read user
	username=$(echo $user|sed 's/.*/\L&/')
	useradd ${username} -m -G www-data
	echo -n "Password: (hit enter to generate a password) "; read password; echo ""
	if [[ ! -z "${password}" ]]; then
	        echo "Setting password to: ${password}"; passwd=${password}
	        echo "${username}:${passwd}"|chpasswd >/dev/null 2>&1
	else
	        echo "Setting password to: ${genpass}"; passwd=${genpass}
	        echo "${username}:${passwd}"|chpasswd >/dev/null 2>&1
	fi
		MD5=`echo ${passwd}|md5sum|awk '{print $1}'`
	fi
	mkdir -p /home/${username}/.config/deluge/
	chown -R ${username}.${username} /home/${username}/.config/
}
function _delugeconf() {
mkdir -p /home/${username}/{downloads,dwatch}
cat >/home/$username/.config/deluge/core.conf<<EOF
{
  "file": 1, 
  "format": 1
}{
  "info_sent": 0.0, 
  "lsd": true, 
  "max_download_speed": -1.0, 
  "send_info": false, 
  "natpmp": true, 
  "move_completed_path": "/home/${username}/downloads", 
  "peer_tos": "0x00", 
  "enc_in_policy": 1, 
  "queue_new_to_top": false, 
  "ignore_limits_on_local_network": true, 
  "rate_limit_ip_overhead": true, 
  "daemon_port": ${dPORT}, 
  "torrentfiles_location": "/home/${username}/dwatch", 
  "max_active_limit": -1, 
  "geoip_db_location": "/usr/share/GeoIP/GeoIP.dat", 
  "upnp": true, 
  "utpex": true, 
  "max_active_downloading": 3, 
  "max_active_seeding": 5, 
  "allow_remote": true, 
  "outgoing_ports": [
    0, 
    0
  ], 
  "enabled_plugins": [], 
  "max_half_open_connections": 50, 
  "download_location": "/home/${username}/downloads", 
  "compact_allocation": false, 
  "max_upload_speed": -1.0, 
  "plugins_location": "/home/${username}/.config/deluge/plugins", 
  "max_connections_global": -1, 
  "enc_prefer_rc4": true, 
  "cache_expiry": 60, 
  "dht": true, 
  "stop_seed_at_ratio": false, 
  "stop_seed_ratio": 2.0, 
  "max_download_speed_per_torrent": -1, 
  "prioritize_first_last_pieces": true, 
  "max_upload_speed_per_torrent": -1, 
  "auto_managed": true, 
  "enc_level": 2, 
  "copy_torrent_file": false, 
  "max_connections_per_second": 50, 
  "listen_ports": [
    6881, 
    6891
  ], 
  "max_connections_per_torrent": -1, 
  "del_copy_torrent_file": false, 
  "move_completed": false, 
  "autoadd_enable": false, 
  "proxies": {
    "peer": {
      "username": "", 
      "password": "", 
      "hostname": "", 
      "type": 0, 
      "port": 8080
    }, 
    "web_seed": {
      "username": "", 
      "password": "", 
      "hostname": "", 
      "type": 0, 
      "port": 8080
    }, 
    "tracker": {
      "username": "", 
      "password": "", 
      "hostname": "", 
      "type": 0, 
      "port": 8080
    }, 
    "dht": {
      "username": "", 
      "password": "", 
      "hostname": "", 
      "type": 0, 
      "port": 8080
    }
  }, 
  "dont_count_slow_torrents": false, 
  "add_paused": false, 
  "random_outgoing_ports": true, 
  "max_upload_slots_per_torrent": -1, 
  "new_release_check": false, 
  "enc_out_policy": 1, 
  "seed_time_ratio_limit": 7.0, 
  "remove_seed_at_ratio": false, 
  "autoadd_location": "/home/${username}/dwatch/", 
  "max_upload_slots_global": 4, 
  "seed_time_limit": 180, 
  "cache_size": 512, 
  "share_ratio_limit": 2.0, 
  "random_port": true, 
  "listen_interface": "${ip}"
}
EOF
}
function _finished() { 
	echo ""; 
	echo "deluged info: user: ${username} pass:${MD5} port: ${dPORT}"
	if [[ ${user} == "yes" ]]; then 
		echo "ssh information: USER: ${username} PASS: ${passwd}"
	fi
	chown -R ${username}.${username} /home/${username}
	service apache2 restart >/dev/null 2>&1
	rm -rf $0 >/dev/null 2>&1
}
function _sysctl() { wget -q4 https://raw.githubusercontent.com/JMSDOnline/quick-box/master/sysctl.conf -O/etc/sysctl.conf; sysctl -p >/dev/null 2>&1 ; echo ${OK} ;}
function _depends() { 
LIST='dstat g++ python-all-dev python-all python-openssl python-simplejson python-setuptools
python-chardet libssl-dev zlib1g-dev libboost-dev libasio-dev libboost-python-dev
libboost-thread-dev python-twisted python-twisted-bin python-twisted-bin-dbg
python-twisted-core python-twisted-conch python-twisted-lore python-twisted-mail
python-twisted-names python-twisted-news python-twisted-runner python-twisted-runner-dbg
python-twisted-web python-twisted-web2 python-twisted-words python-twisted-libravatar python-mako python-xdg
libboost-date-time-dev libboost-filesystem-dev build-essential python-libtorrent'
for depend in $LIST; do
apt-get -q --yes --force-yes install $depend >/dev/null 2>&1
done
}
	
function _delugeinstall() { 
	wget -q http://download.deluge-torrent.org/source/deluge-$VERSION.tar.gz >/dev/null 2>&1
	tar xzf deluge-$VERSION.tar.gz
	cd deluge-$VERSION >/dev/null 2>&1; 
	python setup.py build >/dev/null 2>&1; 
	python setup.py install >/dev/null 2>&1; 
	ldconfig >/dev/null 2>&1
	cd ..
	rm -rf deluge-*
cat >/etc/apache2/sites-enabled/$username.deluge.downloads.conf<<EOF
Alias /${username}.deluge "/home/${username}/downloads/"
	<Directory "/home/${username}/downloads">
		Options Indexes FollowSymLinks MultiViews
		AuthType Digest
		AuthName "rutorrent"
		AuthUserFile '/etc/htpasswd'
		Require valid-user
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>
EOF
}

function _delugeauth() { 
	echo "${username}:${MD5}:10" > /home/${username}/.config/deluge/auth 
}

function _geoip() { 
	wget -q http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
	gunzip GeoLiteCity.dat.gz>/dev/null 2>&1
	mkdir -p /usr/share/GeoIP>/dev/null 2>&1
	mv GeoLiteCity.dat /usr/share/GeoIP/GeoIPCity.dat>/dev/null 2>&1
}

function _upgrade() { 
	apt-get -y clean >/dev/null 2>&1
	apt-get update >/dev/null 2>&1
	apt-get --yes --force-yes upgrade >/dev/null 2>&1
}

echo -n "Installing Deluge-web v$VERSION ... "; echo ""; _locale
echo -n "Performing apt-get update/upgrade ... "; _upgrade; _depends ;echo ${OK}
# echo -n "Setting sysctl.conf ... "; _sysctl
echo -n "Installing GeoLite v6 ... "; _geoip ;echo ${OK}
echo -n "Installing: deluged, deluge-web ... "; _delugeinstall ;echo ${OK}
echo -n "Ready to add the user ... Press ENTER to continue ... "; read nothing ;echo ""; _addduser;_delugeconf;_delugeauth
echo -n "Adding deluge to crontab for ${username} ... "; _cronfile ;echo ${OK}; _finished
